# Generated by Django 4.1.5 on 2023-01-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='image',
            field=models.ImageField(blank=True, max_length=50, upload_to=''),
        ),
    ]
