# Generated by Django 4.1.5 on 2023-01-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0003_alter_productlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
