# Generated by Django 4.1.5 on 2023-01-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productdetails', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductList',
        ),
    ]
