# Generated by Django 4.1.5 on 2023-01-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginformList',
            fields=[
                ('username', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.IntegerField(blank=True, max_length=10)),
                ('submitbutton', models.CharField(blank=True, max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loginformlist',
            },
        ),
    ]
